apiVersion: v1
kind: Pod
metadata:
  labels:
    app: assisted-installer
  name: assisted-installer
spec:
  containers:
  # PostgreSQL Database
  - args:
    - run-postgresql
    image: quay.io/sclorg/postgresql-12-c8s:latest
    name: db
    envFrom:
    - configMapRef:
        name: config
    volumeMounts:
    - mountPath: /var/lib/pgsql/data
      name: pgdata
  
  # Assisted Installer UI
  - image: quay.io/edge-infrastructure/assisted-installer-ui:latest
    name: ui
    ports:
    - hostPort: 8080
    envFrom:
    - configMapRef:
        name: config
  
  # Assisted Image Service
  - image: quay.io/edge-infrastructure/assisted-image-service:latest
    name: image-service
    ports:
    - hostPort: 8888
    envFrom:
    - configMapRef:
        name: config
  
  # Assisted Service (Main API)
  - image: quay.io/edge-infrastructure/assisted-service:latest
    name: service
    ports:
    - hostPort: 8090
    envFrom:
    - configMapRef:
        name: config
  
  volumes:
  - name: pgdata
    hostPath:
      path: /home/brandon/okd-db-data
      type: DirectoryOrCreate
  
  restartPolicy: Always
