#!/bin/bash
# OKD Native Installer - Installation Guide

# The VM has been configured and is now installing OKD 4.20.0-okd-scos.9 using the native installer method.

echo "OKD Single-Node Installation Status"
echo "===================================="
echo ""
echo "Installation Details:"
echo "- Cluster Name: okd-sno"
echo "- Base Domain: thelab.lan"
echo "- Full FQDN: okd-sno.thelab.lan"
echo "- OKD Version: 4.20.0-okd-scos.9"
echo "- FCOS Version: 43.20251024.3.0"
echo "- VM ID: 150 (Proxmox)"
echo "- VM Resources: 8 cores, 16GB RAM, 100GB disk"
echo ""
echo "Installation Process:"
echo "1. FCOS boots from ISO with embedded ignition"
echo "2. System installs to /dev/sda"
echo "3. Bootstrap-in-place installation begins"
echo "4. Single-node cluster comes up"
echo ""
echo "Expected Timeline:"
echo "- Initial boot: ~2-3 minutes"
echo "- Installation to disk: ~5-10 minutes"
echo "- Bootstrap: ~30-45 minutes"
echo "- Total time: ~45-60 minutes"
echo ""
echo "Monitoring Commands:"
echo "===================="
echo ""
echo "# Watch VM console (Proxmox web UI)"
echo "https://192.168.2.196:8006"
echo ""
echo "# SSH to node after it boots (may take 10-15 min for SSH to be available)"
echo "ssh core@192.168.2.205  # or whatever IP DHCP assigns"
echo ""
echo "# Watch bootstrap progress (once SSH is available)"
echo "ssh core@<node-ip> 'journalctl -b -f -u bootkube.service'"
echo ""
echo "# Check cluster operators status (after bootstrap completes)"
echo "export KUBECONFIG=/home/brandon/projects/homelab-helper/proxmox/okd/installer/auth/kubeconfig"
echo "./oc get clusteroperators"
echo "./oc get nodes"
echo ""
echo "Kubeconfig Location:"
echo "===================="
echo "/home/brandon/projects/homelab-helper/proxmox/okd/installer/auth/kubeconfig"
echo ""
echo "Admin Credentials:"
echo "===================="
echo "Username: kubeadmin"
echo "Password: (see auth/kubeadmin-password file)"
cat /home/brandon/projects/homelab-helper/proxmox/okd/installer/auth/kubeadmin-password 2>/dev/null || echo "(not available yet)"
echo ""
echo "Console URL (after installation):"
echo "=================================="
echo "https://console-openshift-console.apps.okd-sno.thelab.lan"
echo ""
echo "Note: You may need to add DNS entries or /etc/hosts entries for:"
echo "- api.okd-sno.thelab.lan -> <node-ip>"
echo "- *.apps.okd-sno.thelab.lan -> <node-ip>"
